x-common-config: &common-config
  network_mode: host
  ipc: host
  restart: always
  env_file:
    - .env # env configuration including namespace, domain id, DDS, etc.

services:
  husarion-ugv-franka-manipulator :
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: husarion-ugv-franka-manipulator-rviz
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - USER=${USER:-root}
    command: >
      ros2 launch husarion_ugv_franka_manipulator_bringup rviz.launch.py
        robot_ip:=${ROBOT_IP}
