x-common-config: &common-config
  network_mode: host
  ipc: host
  restart: always
  env_file:
    - .env # env configuration including namespace, domain id, DDS, etc.

services:
  husarion-ugv-franka-manipulator :
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: husarion-ugv-franka-manipulator
    <<: *common-config
    volumes:
      - ./husarion_ugv_franka_manipulator_bringup/launch:/ros2_ws/src/husarion_ugv_franka_manipulator_bringup/launch
    ulimits:
      rtprio:
        soft: 99
        hard: 99
      memlock:
        soft: -1
        hard: -1
    command: >
      ros2 launch husarion_ugv_franka_manipulator_bringup robot_bringup.launch.py
        robot_model:=${ROBOT_MODEL_NAME} robot_ip:=${ROBOT_IP}